<?php

namespace GenesisCustomizer\Tests;

use Brain\Monkey\Functions;
use function GenesisCustomizer\_get_image_sizes;

/**
 * Class Test_GetImageSizes
 *
 * @package GenesisCustomizer\Tests
 * @group   bootstrap
 */
class Test_GetImageSizes extends Test_Case {

	protected function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub

		Functions\when( 'get_intermediate_image_sizes' )->justReturn( [
			'small',
			'medium',
			'large',
		] );
	}

	/**
	 * Description of expected behavior.
	 *
	 * @since 1.0.0
	 *
	 * @return void
	 */
	public function test_should_append_additional_image_sizes_to_array() {
		$this->assertArrayHasKey( 'custom', _get_image_sizes( [ 'custom' ] ) );
	}

	/**
	 * Description of expected behavior.
	 *
	 * @since 1.0.0
	 *
	 * @return void
	 */
	public function test_should_format_image_labels() {
		$this->assertSame( 'Full', _get_image_sizes()['full'] );
	}

}
